apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "capgemini-assignment.fullname" . }}
  labels:
    app: {{ include "capgemini-assignment.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "capgemini-assignment.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "capgemini-assignment.name" . }}
    spec:
      containers:
        - name: {{ include "capgemini-assignment.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.env.PORT }}
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
