apiVersion: v1
kind: Service
metadata:
  name: capgemini-assignment
spec:
  selector:
    app: capgemini-assignment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
